package ente_share

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"reflect"
	"slices"
	"strings"
	"sync"
	"testing"

	"github.com/OpenListTeam/OpenList/v4/drivers/ente"
	"github.com/OpenListTeam/OpenList/v4/internal/conf"
	"github.com/OpenListTeam/OpenList/v4/internal/model"
	"github.com/OpenListTeam/OpenList/v4/internal/op"
	"github.com/OpenListTeam/OpenList/v4/pkg/http_range"
)

// TestMain loads the minimal global state the driver touches: conf.Conf (used
// by net.NewHttpClient) and the settings cache (used by sign.Sign to sign
// thumbnail proxy URLs). Unit tests run without a database.
func TestMain(m *testing.M) {
	conf.Conf = &conf.Config{}
	op.Cache.SetSetting(conf.LinkExpiration, &model.SettingItem{Key: conf.LinkExpiration, Value: "0"})
	op.Cache.SetSetting(conf.Token, &model.SettingItem{Key: conf.Token, Value: "test-sign-token"})
	os.Exit(m.Run())
}

// Vectors cross-generated by the Go side from the official ente crypto
// implementation (see OpenList-Worker drivers/ente/*_test.ts).
const testCollectionKeyB58 = "4F85ZySpwyY6FuKqoUgmccbBRAXGrgb8pFyjpd5DcNrA"

// f105 single-chunk TagFinal stream: plaintext "hello ente" + 300x0xAB + "tail".
const f105StreamCipher = "iB/auOp6LX43bGJ7cckztmJOlI6FrO9L+qHWkWB3/J9yokKyIECTKX0ZE3+Y9yEsmNO7dSDJM+shcFmNst3WAkQAN59wxrnmQnKEdq0Pzrng0QJjVc3Hc+PSh1ztYO8Pr/IEWggpGoxHCnEwlKh8H2/DWF+H1RwYK+8WkdS2IG4AEpSsUjouHcb53O4wlC+QpkCaE/IsE44Nduf7LzSrv/eniGm3k+ThR5vmMg2SSGiSvZB4Yby4ZeXMlzaKAIomXht/KLVZyzgSgAReyLcGzCV+q3nua/sUa5OI6+xZkIo9S+kFZbpYTDNGV5jJxLl+GDdvYYMg7LrQeHfYDDdtXgQKZktdm6ckMneCzmr1cwHV7Zq/YMAvin1qlamYZGV56Yj8m8GFw+Z7vVaFcaVbs/a40TRZz7KMoVZLJYLechns95dSbrXF7bDJew=="

// f101 thumbnail single-chunk stream: JPEG magic + 28x0x77.
const f101ThumbCipher = "VsiMik6lTV/SfmM2bntaXvF5kzMOMf+do870TdqDqCHiD7TWncAsWHiNCQGBylM84w=="

// uniform three-chunk stream: 50x0x11 TagMessage + 50x0x22 TagPush + "end" TagFinal.
const (
	uniformKeyB64    = "4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8="
	uniformHeaderB64 = "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh"
)

var uniformChunks = []string{
	"Askkcj8p5lO0J3zbGxN1emvwHq7qz5aKIqsYVcE326keGNikEhW2eBhzO7OLRzntdMQ3EQnQgoGdrDx297S4e1ehJQ==",
	"g6nrG76yAEen5phHKK0iDio/xajaWQbUwo0hZ5bX5C+28gvasGgoz3ahOBx9nzdQYBBxM0tE0sLKv+D0IAecLa34hA==",
	"xmThEqyj0lwxHbSwvA1OKsIy9Qo=",
}

// ---------------------------------------------------------------------------
// fixtures
// ---------------------------------------------------------------------------

func f101() ente.EnteDiffFile {
	return ente.EnteDiffFile{
		ID:                 101,
		EncryptedKey:       "42gbAI24STbGiTKDQWTwDb7yiTOwuOG6U01APz9+m5id4c8z93sW9C7ZXgnMhAx7",
		KeyDecryptionNonce: "QUJDREVGR0hJSktMTU5PUFFSU1RVVldY",
		File: &ente.EnteFileAttributes{
			DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA==",
			EncryptedData:    "eA==",
		},
		Thumbnail: &ente.EnteFileAttributes{DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh"},
		Metadata: &ente.EnteFileAttributes{
			EncryptedData:    "Vkx2AcemVk2HMzYIVEtyG7Y80HVJdr215ImyFMeEuHS5+7vnIvyhsDA+rn0db0/D2h0XIjk3MHO+S7FJ5iNM1zEDnhj4/JXofGTM8iPkEaj2T6//Vbkq/tu+UABw8jxmKMACBDOVofln1AvgfR7AWm5G4nPt",
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		PubMagicMetadata: &ente.EnteMagicMetadata{
			Data:   "Vkx2EMq7Tk3BR3UsfC4XC2CZQazp+6aApN6hFo+Ruz/hvLzBLvCw+2VhzSZIO1zI2hsUKzg2MXK/BpSdEn2a9vOMA+jsKFkAqag=",
			Header: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		Info:         &ente.EnteFileInfo{FileSize: 12345, ThumbSize: 100},
		UpdationTime: 1000,
	}
}

func f102() ente.EnteDiffFile {
	return ente.EnteDiffFile{
		ID:                 102,
		EncryptedKey:       "47FcYuaf1B1QYlWIT9tJA9wDtQstNo2tRvmdGjkkMnlAPYmArzMJ5YUfR9c8dsDE",
		KeyDecryptionNonce: "QkNERUZHSElKS0xNTk9QUVJTVFVWV1hZ",
		File: &ente.EnteFileAttributes{
			DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA==",
			EncryptedData:    "eA==",
		},
		Thumbnail: &ente.EnteFileAttributes{DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA=="},
		Metadata: &ente.EnteFileAttributes{
			EncryptedData:    "W9jSAOYeSC8IdzfQSI/EDgocDp2g5H3zC2iz+StVCnKul5OwJm8jgirRB8jSZSKjaa87xr2na9iNzehDb0t4YtseMFPIvoolKSr+6t0DEQiuC/8zZjtpIYimmWkDiCfF4+gIJnokNMZbrms=",
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		Info:         &ente.EnteFileInfo{FileSize: 222},
		UpdationTime: 1050,
	}
}

func f105() ente.EnteDiffFile {
	return ente.EnteDiffFile{
		ID:                 105,
		EncryptedKey:       "2SlMdM4yJlF4vFdbwRiyFDgqbHdG85LEvf2nxsgUizgI3B6PPXaJefenqFRwHFle",
		KeyDecryptionNonce: "RUZHSElKS0xNTk9QUVJTVFVWV1hZWltc",
		File: &ente.EnteFileAttributes{
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
			EncryptedData:    "eA==",
		},
		Thumbnail: &ente.EnteFileAttributes{DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA=="},
		Metadata: &ente.EnteFileAttributes{
			EncryptedData:    "iAydoO9hYX57IiWmswb9cueITxEMK2aDI28cTqKzOWCwZIw7sdoPsO6AiuYBbri1AUoi7LlOui3lv5tAcBUc3YbE8mCyAHdv0+gY7z6WVyB5SJv6zFRe6noEsOrESFCelID0oYRjhgShAA==",
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		PubMagicMetadata: &ente.EnteMagicMetadata{
			Data:   "iAydseJ8eX49Vma9v0CiP6GKU0xKZj3AJ2MZX6TyOkTtK8U77o9R9rPW7L1eOai9AwUxtRH5gaIoXopNwC/Zaovi",
			Header: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		Info:         &ente.EnteFileInfo{FileSize: 999999},
		UpdationTime: 900,
	}
}

// f103 is an isDeleted tombstone: its sparse fields must not trigger decryption.
func f103Deleted() ente.EnteDiffFile {
	return ente.EnteDiffFile{ID: 103, IsDeleted: true, UpdationTime: 1100}
}

// f104 is an encryptedData == "-" tombstone (removed from the album).
func f104Removed() ente.EnteDiffFile {
	f := f102()
	f.ID = 104
	f.UpdationTime = 1080
	f.File = &ente.EnteFileAttributes{DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA==", EncryptedData: "-"}
	return f
}

func pageJSON(t *testing.T, files []ente.EnteDiffFile, hasMore bool) string {
	t.Helper()
	b, err := json.Marshal(ente.EnteDiffResponse{Diff: files, HasMore: hasMore})
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// ---------------------------------------------------------------------------
// mock museum server
// ---------------------------------------------------------------------------

type seenRequest struct {
	url    string
	header http.Header
}

type mockEnte struct {
	*httptest.Server

	mu          sync.Mutex
	seen        []seenRequest
	pages       map[string]string
	infoCode    int
	failCode    int
	failBody    string
	deviceToken string
	bin         map[string][]byte
	fragment    int
}

func newMockEnte(t *testing.T) *mockEnte {
	t.Helper()
	m := &mockEnte{
		pages:    map[string]string{},
		bin:      map[string][]byte{},
		infoCode: 200,
	}
	m.Server = httptest.NewServer(http.HandlerFunc(m.serve))
	t.Cleanup(m.Server.Close)
	return m
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}

func (m *mockEnte) serve(w http.ResponseWriter, r *http.Request) {
	m.mu.Lock()
	m.seen = append(m.seen, seenRequest{url: r.URL.String(), header: r.Header.Clone()})
	m.mu.Unlock()

	if m.deviceToken != "" {
		w.Header().Set("X-Link-Device-Token", m.deviceToken)
	}

	switch {
	case strings.HasPrefix(r.URL.Path, "/bin/"):
		key := strings.TrimPrefix(r.URL.Path, "/bin/")
		body, ok := m.bin[key]
		if !ok {
			http.Error(w, "unknown bin "+key, http.StatusNotFound)
			return
		}
		if m.fragment > 0 {
			// Write in small fragments so the decryptor cannot rely on network
			// chunk boundaries.
			for off := 0; off < len(body); off += m.fragment {
				end := off + m.fragment
				if end > len(body) {
					end = len(body)
				}
				if _, err := w.Write(body[off:end]); err != nil {
					return
				}
				w.(http.Flusher).Flush()
			}
			return
		}
		_, _ = w.Write(body)
	case r.URL.Path == "/public-collection/info":
		w.WriteHeader(m.infoCode)
		_, _ = io.WriteString(w, "{}")
	case r.URL.Path == "/public-collection/diff":
		if m.failCode != 0 {
			w.WriteHeader(m.failCode)
			_, _ = io.WriteString(w, m.failBody)
			return
		}
		since := r.URL.Query().Get("sinceTime")
		body, ok := m.pages[since]
		if !ok {
			http.Error(w, "unexpected request sinceTime="+since, http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, body)
	case strings.HasPrefix(r.URL.Path, "/public-collection/files/download/v3/"):
		id := strings.TrimPrefix(r.URL.Path, "/public-collection/files/download/v3/")
		writeJSON(w, map[string]string{"url": m.URL + "/bin/file-" + id})
	case strings.HasPrefix(r.URL.Path, "/public-collection/files/thumbnail/v3/"):
		id := strings.TrimPrefix(r.URL.Path, "/public-collection/files/thumbnail/v3/")
		writeJSON(w, map[string]string{"url": m.URL + "/bin/thumb-" + id})
	default:
		http.Error(w, "unexpected path "+r.URL.Path, http.StatusNotFound)
	}
}

func (m *mockEnte) requests() []seenRequest {
	m.mu.Lock()
	defer m.mu.Unlock()
	out := make([]seenRequest, len(m.seen))
	copy(out, m.seen)
	return out
}

func (m *mockEnte) urls() []string {
	reqs := m.requests()
	out := make([]string, 0, len(reqs))
	for _, r := range reqs {
		out = append(out, r.url)
	}
	return out
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func apiCtx() context.Context {
	return context.WithValue(context.Background(), conf.ApiUrlKey, "http://127.0.0.1:5244")
}

func newTestDriver(t *testing.T, m *mockEnte, addition Addition) *EnteShare {
	t.Helper()
	d := &EnteShare{Addition: addition}
	if err := d.Init(context.Background()); err != nil {
		t.Fatalf("Init: %v", err)
	}
	// Never touch the database in unit tests.
	d.saveStorage = func() {}
	d.SetStorage(model.Storage{MountPath: "/ente_share"})
	return d
}

func shareAddition(token string) Addition {
	return Addition{
		ShareURL: "https://share.ente.io/c/" + token + "#" + testCollectionKeyB58,
	}
}

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("bad base64 fixture %q: %v", s, err)
	}
	return b
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

func TestEnteShareList(t *testing.T) {
	m := newMockEnte(t)
	// Page 1 advances the watermark to 1100; page 2 only carries entries older
	// than 1100, so the watermark stops advancing and pagination must terminate.
	m.pages["0"] = pageJSON(t, []ente.EnteDiffFile{f101(), f103Deleted(), f105()}, true)
	m.pages["1100"] = pageJSON(t, []ente.EnteDiffFile{f102(), f104Removed()}, true)

	d := newTestDriver(t, m, func() Addition {
		a := shareAddition("Fxtoken1")
		a.Endpoint = m.URL
		return a
	}())

	objs, err := d.List(apiCtx(), &model.Object{Path: d.GetRootPath()}, model.ListArgs{ReqPath: "/"})
	if err != nil {
		t.Fatal(err)
	}
	if len(objs) != 3 {
		t.Fatalf("want 3 objs, got %d: %v", len(objs), objs)
	}
	bySize := map[int64]model.Obj{}
	for _, o := range objs {
		bySize[o.GetSize()] = o
	}
	if o := bySize[12328]; o.GetName() != "日落.jpg" {
		t.Errorf("size 12328 name = %q, want 日落.jpg", o.GetName())
	} else if want := "2024-10-05T06:51:51.111Z"; o.ModTime().UTC().Format("2006-01-02T15:04:05.000Z") != want {
		t.Errorf("size 12345 modified = %v, want %s", o.ModTime(), want)
	}
	if o := bySize[205]; o.GetName() != "日落 (2).jpg" {
		t.Errorf("size 205 name = %q, want 日落 (2).jpg", o.GetName())
	} else if want := "2024-10-04T00:00:00.000Z"; o.ModTime().UTC().Format("2006-01-02T15:04:05.000Z") != want {
		t.Errorf("size 222 modified = %v, want %s", o.ModTime(), want)
	}
	// editedTime == 0 falls back to creationTime; editedName overrides title.
	if o := bySize[999982]; o.GetName() != "holiday video.mp4" {
		t.Errorf("size 999982 name = %q, want holiday video.mp4", o.GetName())
	} else if want := "2024-10-06T13:43:42.222Z"; o.ModTime().UTC().Format("2006-01-02T15:04:05.000Z") != want {
		t.Errorf("size 999982 modified = %v, want %s", o.ModTime(), want)
	}

	for _, o := range objs {
		if o.IsDir() {
			t.Errorf("%s: must not be a dir", o.GetName())
		}
		if u, ok := model.GetUrl(o); ok && u != "" {
			t.Errorf("%s: NoLinkURL driver must not expose a url, got %q", o.GetName(), u)
		}
	}

	names := make([]string, 0, len(objs))
	for _, o := range objs {
		names = append(names, o.GetName())
	}
	// Files are listed name-ascending, matching the worker's default order.
	if want := []string{"holiday video.mp4", "日落 (2).jpg", "日落.jpg"}; !reflect.DeepEqual(names, want) {
		t.Errorf("names = %v, want %v", names, want)
	}

	// Exactly two pages; a third request would fail the mock.
	urls := m.urls()
	if len(urls) != 2 {
		t.Fatalf("requests = %v, want exactly 2", urls)
	}
	if !strings.HasSuffix(urls[0], "/public-collection/diff?sinceTime=0") {
		t.Errorf("urls[0] = %q", urls[0])
	}
	if !strings.HasSuffix(urls[1], "sinceTime=1100") {
		t.Errorf("urls[1] = %q", urls[1])
	}
	h := m.requests()[0].header
	if got := h.Get("X-Auth-Access-Token"); got != "Fxtoken1" {
		t.Errorf("X-Auth-Access-Token = %q, want Fxtoken1", got)
	}
	if got := h.Get("X-Client-Package"); got != "io.ente.photos" {
		t.Errorf("X-Client-Package = %q, want io.ente.photos", got)
	}
	if strings.Contains(h.Get("User-Agent"), "Go-http-client") {
		t.Errorf("User-Agent must not be Go's default, got %q", h.Get("User-Agent"))
	}
}

func TestEnteShareGet(t *testing.T) {
	m := newMockEnte(t)
	m.pages["0"] = pageJSON(t, []ente.EnteDiffFile{f101(), f102()}, false)

	d := newTestDriver(t, m, func() Addition {
		a := shareAddition("Fxtoken2")
		a.Endpoint = m.URL
		return a
	}())

	obj, err := d.Get(apiCtx(), "/日落.jpg")
	if err != nil {
		t.Fatal(err)
	}
	if obj.GetName() != "日落.jpg" || obj.GetSize() != 12328 {
		t.Errorf("get = %s size %d", obj.GetName(), obj.GetSize())
	}
	// Get must build the same thumbnail URL as List: the signed path is the
	// mount path plus the file name, never the full object path.
	thumb, ok := model.GetThumb(obj)
	if !ok {
		t.Fatal("日落.jpg must carry a thumbnail")
	}
	if u, err := url.Parse(thumb); err != nil {
		t.Fatal(err)
	} else if want := "/p/ente_share/日落.jpg"; u.Path != want {
		t.Errorf("get thumb path = %q, want %q", u.Path, want)
	} else if !strings.Contains(u.RawQuery, "type=thumb&sign=") {
		t.Errorf("get thumb query = %q, want type=thumb&sign=", u.RawQuery)
	}

	root, err := d.Get(apiCtx(), "/")
	if err != nil {
		t.Fatal(err)
	}
	if !root.IsDir() {
		t.Error("root must be a dir")
	}

	if _, err := d.Get(apiCtx(), "/nope.jpg"); err == nil {
		t.Error("want not-found error")
	}
}

func TestEnteShareLinkStream(t *testing.T) {
	m := newMockEnte(t)
	m.pages["0"] = pageJSON(t, []ente.EnteDiffFile{f105()}, false)
	m.bin["file-105"] = mustB64(t, f105StreamCipher)
	m.fragment = 7

	d := newTestDriver(t, m, func() Addition {
		a := shareAddition("Fxtoken4")
		a.Endpoint = m.URL
		return a
	}())

	objs, err := d.List(apiCtx(), &model.Object{Path: d.GetRootPath()}, model.ListArgs{ReqPath: "/"})
	if err != nil {
		t.Fatal(err)
	}
	if len(objs) != 1 {
		t.Fatalf("want 1 obj, got %d", len(objs))
	}

	link, err := d.Link(apiCtx(), objs[0], model.LinkArgs{})
	if err != nil {
		t.Fatal(err)
	}
	if link.URL != "" {
		t.Errorf("NoLinkURL driver must not return a URL, got %q", link.URL)
	}
	if link.ContentLength != 999982 {
		t.Errorf("ContentLength = %d, want plaintext size 999982", link.ContentLength)
	}
	if link.RangeReader == nil {
		t.Fatal("RangeReader is nil")
	}

	rc, err := link.RangeReader.RangeRead(apiCtx(), http_range.Range{Length: -1})
	if err != nil {
		t.Fatal(err)
	}
	defer rc.Close()
	got, err := io.ReadAll(rc)
	if err != nil {
		t.Fatal(err)
	}
	want := append([]byte("hello ente"), bytes.Repeat([]byte{0xab}, 300)...)
	want = append(want, []byte("tail")...)
	if !bytes.Equal(got, want) {
		t.Errorf("plaintext mismatch: got %d bytes, want %d", len(got), len(want))
	}

	urls := m.urls()
	wantURLs := []string{
		"/public-collection/diff?sinceTime=0",
		"/public-collection/files/download/v3/105",
		"/bin/file-105",
	}
	if !reflect.DeepEqual(urls, wantURLs) {
		t.Errorf("requests = %v, want %v", urls, wantURLs)
	}
	// The presigned S3 fetch must carry no ente headers at all.
	binReq := m.requests()[2]
	if _, ok := binReq.header["X-Client-Package"]; ok {
		t.Error("presigned fetch must not send X-Client-Package")
	}
	if _, ok := binReq.header["X-Auth-Access-Token"]; ok {
		t.Error("presigned fetch must not send X-Auth-Access-Token")
	}
	if binReq.header.Get("User-Agent") != "" {
		t.Errorf("presigned fetch must not send a User-Agent, got %q", binReq.header.Get("User-Agent"))
	}
}

func TestEnteShareThumb(t *testing.T) {
	m := newMockEnte(t)
	m.pages["0"] = pageJSON(t, []ente.EnteDiffFile{f101(), f102()}, false)
	m.bin["thumb-101"] = mustB64(t, f101ThumbCipher)
	m.fragment = 9

	d := newTestDriver(t, m, func() Addition {
		a := shareAddition("Fxthumb1")
		a.Endpoint = m.URL
		return a
	}())
	ctx := apiCtx()

	objs, err := d.List(ctx, &model.Object{Path: d.GetRootPath()}, model.ListArgs{ReqPath: "/"})
	if err != nil {
		t.Fatal(err)
	}
	byName := map[string]model.Obj{}
	for _, o := range objs {
		byName[o.GetName()] = o
	}

	thumb, ok := model.GetThumb(byName["日落.jpg"])
	if !ok {
		t.Fatal("日落.jpg must carry a thumbnail")
	}
	if !strings.HasPrefix(thumb, "http://127.0.0.1:5244/p/") {
		t.Errorf("thumb = %q, want an /p/ proxy URL", thumb)
	}
	if !strings.Contains(thumb, "type=thumb&sign=") {
		t.Errorf("thumb = %q, want type=thumb&sign=", thumb)
	}
	if got, ok := model.GetThumb(byName["日落 (2).jpg"]); ok && got != "" {
		t.Errorf("日落 (2).jpg thumb = %q, want empty", got)
	}

	link, err := d.Link(ctx, byName["日落.jpg"], model.LinkArgs{Type: "thumb"})
	if err != nil {
		t.Fatal(err)
	}
	if link.ContentLength != 83 {
		t.Errorf("thumb ContentLength = %d, want plaintext thumbSize 83", link.ContentLength)
	}
	rc, err := link.RangeReader.RangeRead(ctx, http_range.Range{Length: -1})
	if err != nil {
		t.Fatal(err)
	}
	got, err := io.ReadAll(rc)
	rc.Close()
	if err != nil {
		t.Fatal(err)
	}
	want := append([]byte{0xff, 0xd8, 0xff, 0xe0}, bytes.Repeat([]byte{0x77}, 28)...)
	if !bytes.Equal(got, want) {
		t.Errorf("thumb plaintext mismatch: got %d bytes, want %d", len(got), len(want))
	}

	if _, err := d.Link(ctx, byName["日落 (2).jpg"], model.LinkArgs{Type: "thumb"}); err == nil ||
		!strings.Contains(err.Error(), "no thumbnail") {
		t.Errorf("err = %v, want no thumbnail", err)
	}
}

func TestEnteShareDeviceToken(t *testing.T) {
	m := newMockEnte(t)
	m.pages["0"] = pageJSON(t, nil, false)
	m.deviceToken = "jwt-issued"

	addition := shareAddition("Fxdev1")
	addition.Endpoint = m.URL
	addition.DeviceToken = "jwt-seeded"
	d := newTestDriver(t, m, addition)
	saved := 0
	d.saveStorage = func() { saved++ }

	if _, err := d.List(apiCtx(), &model.Object{Path: d.GetRootPath()}, model.ListArgs{ReqPath: "/"}); err != nil {
		t.Fatal(err)
	}
	reqs := m.requests()
	if len(reqs) != 1 {
		t.Fatalf("want 1 request, got %d", len(reqs))
	}
	if got := reqs[0].header.Get("X-Auth-Link-Device-Token"); got != "jwt-seeded" {
		t.Errorf("X-Auth-Link-Device-Token = %q, want jwt-seeded", got)
	}
	// The newly issued token must replace the seeded one and be persisted once.
	if got := d.DeviceToken; got != "jwt-issued" {
		t.Errorf("DeviceToken = %q, want jwt-issued", got)
	}
	if saved != 1 {
		t.Errorf("saveStorage calls = %d, want 1", saved)
	}
	if got := d.consumePendingDeviceToken(); got != "" {
		t.Errorf("pending token = %q, want empty after flush", got)
	}
}

func TestEnteShareErrors(t *testing.T) {
	cases := []struct {
		name       string
		status     int
		body       string
		infoStatus int
		want       string
	}{
		{"share expired", 410, "expired", 200, "分享已过期"},
		{"device limit", 403, "Public link device limit reached", 200, "设备数已达上限"},
		{"password protected", 401, "auth required", 200, "密码保护"},
		{"invalid token", 401, "auth required", 401, "token 无效"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := newMockEnte(t)
			m.failCode = tc.status
			m.failBody = tc.body
			m.infoCode = tc.infoStatus

			addition := shareAddition("Fxerr")
			addition.Endpoint = m.URL
			d := newTestDriver(t, m, addition)

			_, err := d.List(apiCtx(), &model.Object{Path: d.GetRootPath()}, model.ListArgs{ReqPath: "/"})
			if err == nil {
				t.Fatal("want error")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error = %q, want substring %q", err.Error(), tc.want)
			}
		})
	}
}

func TestEnteShareRegistration(t *testing.T) {
	ctor, err := op.GetDriver("EnteShare")
	if err != nil {
		t.Fatal(err)
	}
	cfg := ctor().Config()
	if !cfg.OnlyProxy {
		t.Error("OnlyProxy must be true")
	}
	if !cfg.NoUpload {
		t.Error("NoUpload must be true")
	}
	if !cfg.NoLinkURL {
		t.Error("NoLinkURL must be true")
	}
	if !cfg.MustProxy() {
		t.Error("MustProxy must be true")
	}
	if cfg.DefaultRoot != "" {
		t.Errorf("DefaultRoot = %q, want empty", cfg.DefaultRoot)
	}

	info, ok := op.GetDriverInfoMap()["EnteShare"]
	if !ok {
		t.Fatal("EnteShare missing from driverInfoMap")
	}
	var names []string
	for _, item := range info.Additional {
		names = append(names, item.Name)
	}
	for _, want := range []string{"share_url", "endpoint"} {
		if !slices.Contains(names, want) {
			t.Errorf("additional items %v missing %q", names, want)
		}
	}
	if slices.Contains(names, "device_token") {
		t.Error("device_token must be hidden from the admin form")
	}
}
