package ente

import (
	"encoding/base64"
	"encoding/json"
	"testing"
)

// Vectors ported from OpenList-Worker src/backend/drivers/ente/crypto.test.ts.
// ENTE_OFFICIAL comes from ente's official crypto_test.go; GO_VECTOR was
// cross-generated by a Go implementation with identical byte semantics.

const (
	enteOfficialCipher = "KHwRN+RzvTu+jC7mCdkMsqnTPSLvevtZILmcR2OYFbIRPqDyjAl+m8KxD9B5fiEo"
	enteOfficialNonce  = "jgfPDOsQh2VdIHWJVSBicMPF2sQW3HIY"
	enteOfficialKey    = "kercNpvGufMTTHmDwAhz26DgCAvznd1+/buBqKEkWr4="
	enteOfficialPlain  = "O1ObUBMv+SCE1qWHD7+WViEIZcAeTp18Y+m9eMlDE1Y="

	goVectorStreamKey    = "AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA="
	goVectorStreamHeader = "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh"
	goVectorChunk1       = "jKA0U4lNkqZ7gTfna2+aAgc7QnPm/v2IxkHX"
	goVectorChunk2       = "EMoz2K+S3Pufd5g1O9VgB2ALj1oNkc8/VoBb483AWxJ1rdD3/314x+pwNXCaxGt/+4C7TVKKouEIi1IoOLYR/W+OB3uoopGxwAQm1zqJBHoUV4SlufREPBfq+ds/qZaKh5T+4BFOsqUlIfmb65mR3rya6dGRsSsLT60X3Ur3JuivpvDBPH80wjPmGFMWwGUIpbKJmr9MHcFd+VTlF+htfYHdxcEMWhAsGkfmWTL/0xfbeCcgGlYuGIn5Q7epm0G6x+acYMBPW8TGc6ICQy4SaCYKha7drZPeRifiBPgyjZ2j3eoSjyCm5CFBS+EKNIRGJmqhjS/BdKfp7/+CjP/NRlKy0U2CmuHVQPu/ucD4b8tc0lqfhVWuE5NOo2fBzkrZdFx2Nn1fG/LTB9TV2zJQyd+RjpuBUjo9Fc5VQ3o="
	goVectorChunk3       = "OYwhyP0scStd4uUz8e41bNOdruWq"
	goVectorMetaCipher   = "j7NzS4xW3qY3z3DSYPeMnB3fJcQgp73Y2/Jz0g5fxg1zcpaSomd8tkDfzeBAqABwAbwaj577i7n13sDYWYQ1jAoUNRUZRLs0oHr9enR8fRrOpc4vL+0IdXmDAlZDclhymiGWFL1HWjc1Bf/JvrT15mcZMmBKwXHrYm+MhQ=="
	goVectorMetaPlain    = `{"title":"照片 001.jpg","creationTime":1728000000000000,"modificationTime":1728000000000000,"fileType":0}`
	goVectorSbKey        = "yMfGxcTDwsHAv769vLu6ubi3trW0s7KxsK+urayrqqk="
	goVectorSbNonce      = "AAMGCQwPEhUYGx4hJCcqLTAzNjk8P0JF"
	goVectorSbCipher     = "g0SCH0FwUOTSCqtg7G/GICY7T+HH5xc/X9FPjbbyfA6rmyl76Q=="
	goVectorBoxPK        = "3e61xxEn4GLG/2Pm5ZsfMxIHWsIp8g2SW7auyHxVAB8="
	goVectorBoxSK        = "EGyImlC8eY6ZsO9Ku51ee+ciOW6Zdy1GxnDT4Vzqsw4="
	goVectorBoxSealed    = "5TgH4cvfF2chnlxDQRjVzKpPoD8n/r5LmoA3THYylCaK0ViW1mV211yD+QOuN4N9sccp716+ZIAiCH/76cP7vPU69QNE"

	// collectionKey fixture from OpenList-Worker ente_share/driver.test.ts
	collectionKeyB58 = "4F85ZySpwyY6FuKqoUgmccbBRAXGrgb8pFyjpd5DcNrA"
)

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("decode base64 %q: %v", s, err)
	}
	return b
}

func TestSecretboxOpenEnteOfficial(t *testing.T) {
	plain, err := secretboxOpen(mustB64(t, enteOfficialCipher), mustB64(t, enteOfficialNonce), mustB64(t, enteOfficialKey))
	if err != nil {
		t.Fatalf("secretboxOpen: %v", err)
	}
	if got := base64.StdEncoding.EncodeToString(plain); got != enteOfficialPlain {
		t.Fatalf("plain mismatch: got %s want %s", got, enteOfficialPlain)
	}
}

func TestSecretboxOpenGoVector(t *testing.T) {
	plain, err := secretboxOpen(mustB64(t, goVectorSbCipher), mustB64(t, goVectorSbNonce), mustB64(t, goVectorSbKey))
	if err != nil {
		t.Fatalf("secretboxOpen: %v", err)
	}
	if string(plain) != "ente secretbox vector" {
		t.Fatalf("plain mismatch: got %q", plain)
	}
}

func TestSecretboxOpenRejectsTamperedCiphertext(t *testing.T) {
	cipher := mustB64(t, goVectorSbCipher)
	cipher[3] ^= 0xff
	if _, err := secretboxOpen(cipher, mustB64(t, goVectorSbNonce), mustB64(t, goVectorSbKey)); err == nil {
		t.Fatal("expected error for tampered ciphertext")
	}
}

func TestSealedBoxOpenGoVector(t *testing.T) {
	plain, err := sealedBoxOpen(mustB64(t, goVectorBoxSealed), mustB64(t, goVectorBoxPK), mustB64(t, goVectorBoxSK))
	if err != nil {
		t.Fatalf("sealedBoxOpen: %v", err)
	}
	if string(plain) != "ente sealedbox vector" {
		t.Fatalf("plain mismatch: got %q", plain)
	}
}

func TestSecretstreamMultiChunk(t *testing.T) {
	d, err := newStreamDecryptor(mustB64(t, goVectorStreamKey), mustB64(t, goVectorStreamHeader))
	if err != nil {
		t.Fatalf("newStreamDecryptor: %v", err)
	}
	plain, tag, err := d.pull(mustB64(t, goVectorChunk1))
	if err != nil {
		t.Fatalf("pull chunk1: %v", err)
	}
	if tag != tagMessage {
		t.Fatalf("chunk1 tag: got %d want %d", tag, tagMessage)
	}
	if string(plain) != "hello ente" {
		t.Fatalf("chunk1 plain: got %q", plain)
	}

	plain, tag, err = d.pull(mustB64(t, goVectorChunk2))
	if err != nil {
		t.Fatalf("pull chunk2: %v", err)
	}
	if tag != tagPush {
		t.Fatalf("chunk2 tag: got %d want %d", tag, tagPush)
	}
	if len(plain) != 300 {
		t.Fatalf("chunk2 length: got %d want 300", len(plain))
	}
	for _, b := range plain {
		if b != 0xab {
			t.Fatalf("chunk2 content: got %#x want 0xab", b)
		}
	}

	plain, tag, err = d.pull(mustB64(t, goVectorChunk3))
	if err != nil {
		t.Fatalf("pull chunk3: %v", err)
	}
	if tag != tagFinal {
		t.Fatalf("chunk3 tag: got %d want %d", tag, tagFinal)
	}
	if string(plain) != "tail" {
		t.Fatalf("chunk3 plain: got %q", plain)
	}
}

func TestSecretstreamRejectsOutOfOrderChunk(t *testing.T) {
	d, err := newStreamDecryptor(mustB64(t, goVectorStreamKey), mustB64(t, goVectorStreamHeader))
	if err != nil {
		t.Fatalf("newStreamDecryptor: %v", err)
	}
	if _, _, err := d.pull(mustB64(t, goVectorChunk3)); err == nil {
		t.Fatal("expected error for out-of-order chunk")
	}
}

func TestSecretstreamRejectsTamperedCiphertext(t *testing.T) {
	d, err := newStreamDecryptor(mustB64(t, goVectorStreamKey), mustB64(t, goVectorStreamHeader))
	if err != nil {
		t.Fatalf("newStreamDecryptor: %v", err)
	}
	cipher := mustB64(t, goVectorChunk1)
	cipher[5] ^= 0x01
	if _, _, err := d.pull(cipher); err == nil {
		t.Fatal("expected error for tampered ciphertext")
	}
}

func TestDecryptMetadata(t *testing.T) {
	plain, err := decryptMetadata(mustB64(t, goVectorStreamKey), mustB64(t, goVectorStreamHeader), mustB64(t, goVectorMetaCipher))
	if err != nil {
		t.Fatalf("decryptMetadata: %v", err)
	}
	if string(plain) != goVectorMetaPlain {
		t.Fatalf("plain mismatch: got %s want %s", plain, goVectorMetaPlain)
	}
	var meta struct {
		Title        string `json:"title"`
		CreationTime int64  `json:"creationTime"`
	}
	if err := json.Unmarshal(plain, &meta); err != nil {
		t.Fatalf("unmarshal metadata: %v", err)
	}
	if meta.Title != "照片 001.jpg" {
		t.Fatalf("title: got %q", meta.Title)
	}
	if meta.CreationTime != 1728000000000000 {
		t.Fatalf("creationTime: got %d", meta.CreationTime)
	}
}

func TestBs58DecodeCollectionKey(t *testing.T) {
	key, err := bs58Decode(collectionKeyB58)
	if err != nil {
		t.Fatalf("bs58Decode: %v", err)
	}
	if len(key) != 32 {
		t.Fatalf("collection key length: got %d want 32", len(key))
	}
}

func TestDecryptedSize(t *testing.T) {
	oneChunk := int64(cipherChunkSize - 100)
	cases := []struct {
		name string
		in   int64
		want int64
	}{
		{"zero", 0, 0},
		{"negative", -1, 0},
		{"single chunk", oneChunk, oneChunk - abYTES},
		{"exact full chunk", int64(cipherChunkSize), int64(cipherChunkSize) - abYTES},
		{"two chunks", int64(cipherChunkSize) + 1, int64(cipherChunkSize) + 1 - 2*abYTES},
	}
	for _, c := range cases {
		if got := decryptedSize(c.in); got != c.want {
			t.Errorf("%s: decryptedSize(%d) = %d, want %d", c.name, c.in, got, c.want)
		}
	}
}
