package ente

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"slices"
	"strings"
	"sync"
	"testing"

	"github.com/OpenListTeam/OpenList/v4/internal/conf"
	"github.com/OpenListTeam/OpenList/v4/internal/driver"
	"github.com/OpenListTeam/OpenList/v4/internal/model"
	"github.com/OpenListTeam/OpenList/v4/internal/op"
	"github.com/OpenListTeam/OpenList/v4/pkg/http_range"
	log "github.com/sirupsen/logrus"
)

// TestMain loads the minimal global state the driver touches: conf.Conf (used by
// net.NewHttpClient) and the settings cache (used by sign.Sign to sign thumbnail
// proxy URLs). Unit tests run without a database.
func TestMain(m *testing.M) {
	conf.Conf = &conf.Config{}
	op.Cache.SetSetting(conf.LinkExpiration, &model.SettingItem{Key: conf.LinkExpiration, Value: "0"})
	op.Cache.SetSetting(conf.Token, &model.SettingItem{Key: conf.Token, Value: "test-sign-token"})
	os.Exit(m.Run())
}

// Vectors cross-generated by the Go side from the official ente crypto
// implementation (see OpenList-Worker drivers/ente/*_test.ts).
const (
	masterKeyB64 = "MDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk8="
	boxSecretB64 = "5ofJ9bTbiYvoZrju4m9JN+OlwCRPrSIcxOWG+p3v6Nw="
)

// ---------------------------------------------------------------------------
// fixtures
// ---------------------------------------------------------------------------

// albumA is an ordinary album owned by the account, key wrapped with the master
// key. Its name decrypts to "旅行 2024".
func albumA() EnteCollection {
	return EnteCollection{
		ID:                  9001,
		Owner:               EnteCollectionUser{ID: 1},
		EncryptedKey:        "JrsA7ZBGK6ky0JlsfAAceY/43PqZYalQFCO7+Kkp9G2H9lu2hv1mPQESt/jj3EaT",
		KeyDecryptionNonce:  "YGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3",
		EncryptedName:       "tZKjtQly3bNkb8lJOjRe7MVlF8lQyr+P17jy",
		NameDecryptionNonce: "cHFyc3R1dnd4eXp7fH1+f4CBgoOEhYaH",
		Type:                "album",
		UpdationTime:        5000000000000,
	}
}

// albumHidden reuses album A's key and name, so it dedupes to "旅行 2024 (2)",
// but carries magicMetadata visibility=2.
func albumHidden() EnteCollection {
	c := albumA()
	c.ID = 9003
	c.UpdationTime = 7000000000000
	c.MagicMetadata = &EnteMagicMetadata{
		Data:   "Vkx2A8ehU0rMZX01YC4XG/vrz88XWTbDwMfNugrG0BhF",
		Header: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
	}
	return c
}

// albumB is a shared album: its key is sealed-box encrypted for the account's
// public key and there is no keyDecryptionNonce, so secret_key is required.
func albumB() EnteCollection {
	return EnteCollection{
		ID:                  9002,
		Owner:               EnteCollectionUser{ID: 2},
		EncryptedKey:        "eMolMegYpR4eFvqkNK3t5x9MXd9hEhEf2VGsIHBlexT4Zn7jp5ZcQoCg04bvEjwqfcLbkNZ5jLBGECtWALta2fIH0jcBWUW+Exo26ypJbtM=",
		EncryptedName:       "6yejXEej6slfscu4I6kdCzZMFY88M0GrSeixXw==",
		NameDecryptionNonce: "gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaX",
		Type:                "album",
		UpdationTime:        6000000000000,
	}
}

// f201 lives in album A and decrypts to "账号文件.jpg" with a thumbnail.
func f201() EnteDiffFile {
	return EnteDiffFile{
		ID:                 201,
		CollectionID:       9001,
		EncryptedKey:       "Pdsr040fkgp9Ebj91NOpmDQ4kz21LWO82wStHXT3vaUiqnN9A3X3zlFBny5o0GTm",
		KeyDecryptionNonce: "RkdISUpLTE1OT1BRUlNUVVZXWFlaW1xd",
		File: &EnteFileAttributes{
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
			EncryptedData:    "eA==",
		},
		Thumbnail: &EnteFileAttributes{DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh"},
		Metadata: &EnteFileAttributes{
			EncryptedData:    "ttnMWS2RgZy0q4dMPwHIPR8RaQ3QXw9RMyh0GPeE5JuDtFY+BRaxGKyGNvFbk7TDMwMat9WAfvl932FKw+WCPoIlaDq2zh1XDjnK6VOWJAXxCzMLEjUfO7qOChQhf59GR2JmS7SaEOVP+CD9",
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		PubMagicMetadata: &EnteMagicMetadata{
			Data:   "ttnMSCCMmZzy38RoF2StL8eU4YIvj8vrlq+9y7ia/ZPPzB02BF3/TP/gZ6wOgb7CNAESttSBf+Rugz8fm7LaIER/3nlOg46F1fqZHcUiTUM=",
			Header: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		Info:         &EnteFileInfo{FileSize: 12345, ThumbSize: 100},
		UpdationTime: 1000,
	}
}

// f202 decrypts to "IMG_002.jpg" and has no thumbnail.
func f202() EnteDiffFile {
	return EnteDiffFile{
		ID:                 202,
		CollectionID:       9001,
		EncryptedKey:       "PRBsq9qgnmzXoqxvs1bzA7kMCRzYjz+byfwoFCs0Nrs0lxNhWk7BBczuzdqWlxLg",
		KeyDecryptionNonce: "R0hJSktMTU5PUFFSU1RVVldYWVpbXF1e",
		File: &EnteFileAttributes{
			DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA==",
			EncryptedData:    "eA==",
		},
		Metadata: &EnteFileAttributes{
			EncryptedData:    "yhn2nQFByEKIcFpUw7LNeKUZP0/Ly7PFkLrB146DEGtR3/PDW1ob5DVxsMBLmbGziIp6jUwCijD3nJlUNjsJJueQawCvFcUDWx4xyCgV49rwHNCPHFgbeL6xTrDkNXT+QgAKdLSVMwqbq/Lt",
			DecryptionHeader: "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh",
		},
		Info:         &EnteFileInfo{FileSize: 222},
		UpdationTime: 1050,
	}
}

// f203Deleted is an isDeleted tombstone: its sparse fields must not trigger
// decryption.
func f203Deleted() EnteDiffFile {
	return EnteDiffFile{ID: 203, CollectionID: 9001, IsDeleted: true, UpdationTime: 1100}
}

// f204Removed is an encryptedData == "-" tombstone (removed from the album).
func f204Removed() EnteDiffFile {
	f := f202()
	f.ID = 204
	f.UpdationTime = 1080
	f.File = &EnteFileAttributes{DecryptionHeader: "AAAAAAAAAAAAAAAAAAAAAA==", EncryptedData: "-"}
	return f
}

// stream201 is a single-chunk TagFinal secretstream whose plaintext is
// "acct-stream-201", encrypted with f201's file key.
const (
	stream201Header = "AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qh"
	stream201Cipher = "tsONTjDIno3k9MRoX3SnPHeoi8kKcsiRSs3ssIDeyBs="
	stream201Plain  = "acct-stream-201"
)

func collectionsJSON(t *testing.T, cs []EnteCollection) string {
	t.Helper()
	b, err := json.Marshal(map[string]any{"collections": cs})
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func pageJSON(t *testing.T, files []EnteDiffFile, hasMore bool) string {
	t.Helper()
	b, err := json.Marshal(EnteDiffResponse{Diff: files, HasMore: hasMore})
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// ---------------------------------------------------------------------------
// mock museum server
// ---------------------------------------------------------------------------

type seenRequest struct {
	url    string
	header http.Header
}

type mockEnte struct {
	*httptest.Server

	mu          sync.Mutex
	seen        []seenRequest
	collections string
	// pages is indexed by "<collectionID>:<sinceTime>"; a request for a page
	// that is not listed fails, which pins down pagination termination.
	pages    map[string]string
	bin      map[string][]byte
	fragment int
	// keyAttrs is served from /users/session-validity/v2; empty means 401
	// (invalid token).
	keyAttrs string
}

func newMockEnte(t *testing.T) *mockEnte {
	t.Helper()
	m := &mockEnte{pages: map[string]string{}, bin: map[string][]byte{}}
	m.Server = httptest.NewServer(http.HandlerFunc(m.serve))
	t.Cleanup(m.Server.Close)
	return m
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}

func (m *mockEnte) serve(w http.ResponseWriter, r *http.Request) {
	m.mu.Lock()
	m.seen = append(m.seen, seenRequest{url: r.URL.String(), header: r.Header.Clone()})
	m.mu.Unlock()

	switch {
	case strings.HasPrefix(r.URL.Path, "/bin/"):
		key := strings.TrimPrefix(r.URL.Path, "/bin/")
		body, ok := m.bin[key]
		if !ok {
			http.Error(w, "unknown bin "+key, http.StatusNotFound)
			return
		}
		if m.fragment > 0 {
			// Write in small fragments so the decryptor cannot rely on network
			// chunk boundaries.
			for off := 0; off < len(body); off += m.fragment {
				end := min(off+m.fragment, len(body))
				if _, err := w.Write(body[off:end]); err != nil {
					return
				}
				w.(http.Flusher).Flush()
			}
			return
		}
		_, _ = w.Write(body)
	case r.URL.Path == "/users/session-validity/v2":
		if m.keyAttrs == "" {
			http.Error(w, "invalid token", http.StatusUnauthorized)
			return
		}
		writeJSON(w, json.RawMessage(m.keyAttrs))
	case r.URL.Path == "/collections/v2":
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, m.collections)
	case r.URL.Path == "/collections/v2/diff":
		key := r.URL.Query().Get("collectionID") + ":" + r.URL.Query().Get("sinceTime")
		body, ok := m.pages[key]
		if !ok {
			http.Error(w, "unexpected request "+key, http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, body)
	case strings.HasPrefix(r.URL.Path, "/files/download/v3/"):
		writeJSON(w, map[string]string{"url": m.URL + "/bin/file"})
	case strings.HasPrefix(r.URL.Path, "/files/thumbnail/v3/"):
		writeJSON(w, map[string]string{"url": m.URL + "/bin/thumb"})
	default:
		http.Error(w, "unexpected path "+r.URL.Path, http.StatusNotFound)
	}
}

func (m *mockEnte) requests() []seenRequest {
	m.mu.Lock()
	defer m.mu.Unlock()
	out := make([]seenRequest, len(m.seen))
	copy(out, m.seen)
	return out
}

func (m *mockEnte) urls() []string {
	reqs := m.requests()
	out := make([]string, 0, len(reqs))
	for _, r := range reqs {
		out = append(out, r.url)
	}
	return out
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func apiCtx() context.Context {
	return context.WithValue(context.Background(), conf.ApiUrlKey, "http://127.0.0.1:5244")
}

// captureLogs redirects the global logrus output so tests can assert warnings.
func captureLogs(t *testing.T) *bytes.Buffer {
	t.Helper()
	buf := &bytes.Buffer{}
	prevOut := log.StandardLogger().Out
	prevFmt := log.StandardLogger().Formatter
	log.SetOutput(buf)
	log.SetFormatter(&log.TextFormatter{DisableColors: true})
	t.Cleanup(func() {
		log.SetOutput(prevOut)
		log.SetFormatter(prevFmt)
	})
	return buf
}

func accountAddition(token, endpoint string) Addition {
	return Addition{
		RootPath:  driver.RootPath{RootFolderPath: "root"},
		Endpoint:  endpoint,
		Token:     token,
		MasterKey: masterKeyB64,
	}
}

func newTestDriver(t *testing.T, addition Addition) *Ente {
	t.Helper()
	d := &Ente{Addition: addition}
	if err := d.Init(context.Background()); err != nil {
		t.Fatalf("Init: %v", err)
	}
	d.SetStorage(model.Storage{MountPath: "/ente"})
	return d
}

// newMockWithAccount wires a mock server carrying album A (with f201/f202 and
// their tombstones), the hidden album and shared album B.
func newMockWithAccount(t *testing.T) *mockEnte {
	t.Helper()
	m := newMockEnte(t)
	m.collections = collectionsJSON(t, []EnteCollection{albumA(), albumB(), albumHidden()})
	// Page 1 advances the watermark to 1100; page 2 only carries entries older
	// than 1100, so the watermark stops advancing and pagination must terminate.
	m.pages["9001:0"] = pageJSON(t, []EnteDiffFile{f201(), f203Deleted()}, true)
	m.pages["9001:1100"] = pageJSON(t, []EnteDiffFile{f202(), f204Removed()}, false)
	m.bin["file"] = mustB64(t, stream201Cipher)
	m.bin["thumb"] = mustB64(t, stream201Cipher)
	return m
}

func names(objs []model.Obj) []string {
	out := make([]string, 0, len(objs))
	for _, o := range objs {
		out = append(out, o.GetName())
	}
	return out
}

func listRoot(t *testing.T, d *Ente) []model.Obj {
	t.Helper()
	objs, err := d.List(apiCtx(), &model.Object{Path: d.GetRootPath()}, model.ListArgs{ReqPath: "/"})
	if err != nil {
		t.Fatalf("List root: %v", err)
	}
	return objs
}

func listAlbum(t *testing.T, d *Ente, name string) []model.Obj {
	t.Helper()
	objs, err := d.List(apiCtx(), &model.Object{Path: "/" + name, IsFolder: true}, model.ListArgs{ReqPath: "/" + name})
	if err != nil {
		t.Fatalf("List %s: %v", name, err)
	}
	return objs
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

func TestEnteListCollections(t *testing.T) {
	m := newMockWithAccount(t)
	logs := captureLogs(t)

	d := newTestDriver(t, accountAddition("Fxacct1", m.URL))
	objs := listRoot(t, d)
	if got, want := names(objs), []string{"旅行 2024"}; !slices.Equal(got, want) {
		t.Errorf("root names = %q, want %q", got, want)
	}
	for _, o := range objs {
		if !o.IsDir() {
			t.Errorf("%s is not a folder", o.GetName())
		}
	}
	// The shared album cannot be opened without secret_key: it is skipped with a
	// warning naming the album, not silently dropped.
	if got := logs.String(); !strings.Contains(got, "9002") {
		t.Errorf("logs = %q, want a warning naming album 9002", got)
	}
	if urls := m.urls(); !slices.Contains(urls, "/collections/v2?sinceTime=0") {
		t.Errorf("urls = %q, want /collections/v2?sinceTime=0", urls)
	}
	if got := m.requests()[0].header.Get("X-Auth-Token"); got != "Fxacct1" {
		t.Errorf("X-Auth-Token = %q, want Fxacct1", got)
	}
}

func TestEnteListCollectionsWithSecretKey(t *testing.T) {
	m := newMockWithAccount(t)

	addition := accountAddition("Fxacct1", m.URL)
	addition.SecretKey = boxSecretB64
	d := newTestDriver(t, addition)
	// Collections are listed name-ascending, matching the worker's default order.
	if got, want := names(listRoot(t, d)), []string{"Shared Album", "旅行 2024"}; !slices.Equal(got, want) {
		t.Errorf("root names = %q, want %q", got, want)
	}
}

func TestEnteListCollectionsShowHidden(t *testing.T) {
	m := newMockWithAccount(t)

	addition := accountAddition("Fxacct1", m.URL)
	addition.SecretKey = boxSecretB64
	addition.ShowHidden = true
	d := newTestDriver(t, addition)
	// The hidden album reuses album A's name, so dedupe must run before the
	// hidden filter: the visible album keeps the unsuffixed name.
	want := []string{"Shared Album", "旅行 2024", "旅行 2024 (2)"}
	if got := names(listRoot(t, d)); !slices.Equal(got, want) {
		t.Errorf("root names = %q, want %q", got, want)
	}
}

func TestEnteListFiles(t *testing.T) {
	m := newMockWithAccount(t)
	d := newTestDriver(t, accountAddition("Fxacct1", m.URL))

	objs := listAlbum(t, d, "旅行 2024")
	// Files are listed name-ascending, matching the worker's default order.
	if got, want := names(objs), []string{"IMG_002.jpg", "账号文件.jpg"}; !slices.Equal(got, want) {
		t.Fatalf("album names = %q, want %q", got, want)
	}
	bySize := map[int64]model.Obj{}
	for _, o := range objs {
		bySize[o.GetSize()] = o
	}
	file, ok := bySize[12328]
	if !ok {
		t.Fatalf("no object of size 12328 in %q", names(objs))
	}
	if got, want := file.ModTime().UTC().Format("2006-01-02T15:04:05.000Z"), "2024-10-05T06:51:51.111Z"; got != want {
		t.Errorf("mod time = %s, want %s", got, want)
	}
	// Both pages must be fetched, and the watermark must advance between them.
	urls := m.urls()
	if !slices.Contains(urls, "/collections/v2/diff?collectionID=9001&sinceTime=0") {
		t.Errorf("urls = %q, want the first diff page", urls)
	}
	if !slices.Contains(urls, "/collections/v2/diff?collectionID=9001&sinceTime=1100") {
		t.Errorf("urls = %q, want the second diff page", urls)
	}
	// The second page reports hasMore=false, so pagination must stop there
	// instead of walking backwards looking for older entries.
	if n := strings.Count(strings.Join(urls, "\n"), "/collections/v2/diff?collectionID=9001"); n != 2 {
		t.Errorf("diff requests = %d, want 2 (pagination must terminate)", n)
	}
}

func TestEnteGet(t *testing.T) {
	m := newMockWithAccount(t)
	d := newTestDriver(t, accountAddition("Fxacct1", m.URL))

	// op.Get resolves the mount root itself; the driver mirrors that fallback.
	root, err := d.Get(apiCtx(), "/")
	if err != nil {
		t.Fatalf("Get /: %v", err)
	}
	if !root.IsDir() || root.GetPath() != "root" {
		t.Errorf("Get / = %+v, want the root folder", root)
	}

	album, err := d.Get(apiCtx(), "/旅行 2024")
	if err != nil {
		t.Fatalf("Get album: %v", err)
	}
	if !album.IsDir() || album.GetName() != "旅行 2024" {
		t.Errorf("Get album = %+v, want folder 旅行 2024", album)
	}

	file, err := d.Get(apiCtx(), "/旅行 2024/账号文件.jpg")
	if err != nil {
		t.Fatalf("Get file: %v", err)
	}
	if file.IsDir() || file.GetSize() != 12328 {
		t.Errorf("Get file = %+v, want the 12328-byte file", file)
	}
	// The thumbnail is advertised as a signed local proxy URL.
	thumb, ok := model.GetThumb(file)
	if !ok {
		t.Fatal("file has no thumbnail")
	}
	if !strings.Contains(thumb, "type=thumb") || !strings.Contains(thumb, "sign=") {
		t.Errorf("thumb = %q, want a signed type=thumb proxy URL", thumb)
	}
	if !strings.HasSuffix(strings.Split(thumb, "?")[0], "/p/ente/%E6%97%85%E8%A1%8C%202024/%E8%B4%A6%E5%8F%B7%E6%96%87%E4%BB%B6.jpg") {
		t.Errorf("thumb path = %q, want the /p proxy path of the file", thumb)
	}

	if _, err := d.Get(apiCtx(), "/不存在"); err == nil {
		t.Error("Get /不存在 = nil error, want ObjectNotFound")
	}
}

func TestEnteLinkStream(t *testing.T) {
	m := newMockWithAccount(t)
	m.fragment = 7
	d := newTestDriver(t, accountAddition("Fxacct1", m.URL))

	objs := listAlbum(t, d, "旅行 2024")
	var file model.Obj
	for _, o := range objs {
		if o.GetName() == "账号文件.jpg" {
			file = o
		}
	}
	if file == nil {
		t.Fatal("账号文件.jpg not found")
	}

	for _, tc := range []struct{ typ, bin string }{{"", "/bin/file"}, {"thumb", "/bin/thumb"}} {
		link, err := d.Link(apiCtx(), file, model.LinkArgs{Type: tc.typ})
		if err != nil {
			t.Fatalf("Link(%q): %v", tc.typ, err)
		}
		if link.RangeReader == nil {
			t.Fatalf("Link(%q) returned no RangeReader", tc.typ)
		}
		rc, err := link.RangeReader.RangeRead(apiCtx(), http_range.Range{Length: -1})
		if err != nil {
			t.Fatalf("RangeRead(%q): %v", tc.typ, err)
		}
		plain, err := io.ReadAll(rc)
		if err != nil {
			t.Fatalf("read(%q): %v", tc.typ, err)
		}
		_ = rc.Close()
		if string(plain) != stream201Plain {
			t.Errorf("Link(%q) plaintext = %q, want %q", tc.typ, plain, stream201Plain)
		}
		urls := m.urls()
		if !slices.Contains(urls, tc.bin) {
			t.Errorf("urls = %q, want %s", urls, tc.bin)
		}
	}

	urls := m.urls()
	if !slices.Contains(urls, "/files/download/v3/201") {
		t.Errorf("urls = %q, want the download v3 endpoint", urls)
	}
	if !slices.Contains(urls, "/files/thumbnail/v3/201") {
		t.Errorf("urls = %q, want the thumbnail v3 endpoint", urls)
	}

	// A file without a thumbnail must be rejected explicitly.
	var noThumb model.Obj
	for _, o := range objs {
		if o.GetName() == "IMG_002.jpg" {
			noThumb = o
		}
	}
	if noThumb == nil {
		t.Fatal("IMG_002.jpg not found")
	}
	if _, err := d.Link(apiCtx(), noThumb, model.LinkArgs{Type: "thumb"}); err == nil ||
		!strings.Contains(err.Error(), "no thumbnail") {
		t.Errorf("Link(thumb) err = %v, want no thumbnail", err)
	}
}

func TestEnteInitTokenPassword(t *testing.T) {
	acc := newSrpAccount(t, testEmail, testPassword)
	m := newMockEnte(t)
	m.collections = collectionsJSON(t, []EnteCollection{albumA()})
	m.pages["9001:0"] = pageJSON(t, []EnteDiffFile{}, false)
	attrs, err := json.Marshal(map[string]any{"hasSetKeys": true, "keyAttributes": acc.keyAttrs})
	if err != nil {
		t.Fatal(err)
	}
	m.keyAttrs = string(attrs)

	addition := accountAddition(acc.tokenB64, m.URL)
	addition.Password = testPassword
	addition.MasterKey = ""
	d := newTestDriver(t, addition)
	if !bytes.Equal(d.masterKey, acc.masterKey) {
		t.Error("master key does not match the account master key")
	}
	if len(d.secretKey) == 0 {
		t.Error("secret key was not decrypted")
	}
	// The fast path must not persist keys back into the config.
	if addition.MasterKey != "" || addition.SecretKey != "" {
		t.Error("keys leaked into the stored addition")
	}
}

func TestEnteInitTokenInvalidNoEmail(t *testing.T) {
	m := newMockEnte(t)

	addition := accountAddition("Fxacct1", m.URL)
	addition.Password = testPassword
	addition.MasterKey = ""
	d := &Ente{Addition: addition}
	err := d.Init(context.Background())
	if err == nil {
		t.Fatal("Init = nil error, want token-invalid error")
	}
	if !strings.Contains(err.Error(), "refresh the token") || !strings.Contains(err.Error(), "email") {
		t.Errorf("err = %v, want a hint to refresh the token or add email", err)
	}
}

func TestEnteInitPasswordOnly(t *testing.T) {
	d := &Ente{Addition: Addition{Password: testPassword}}
	err := d.Init(context.Background())
	if err == nil {
		t.Fatal("Init = nil error, want insufficient-credentials error")
	}
	if !strings.Contains(err.Error(), "no way to authenticate") {
		t.Errorf("err = %v, want no way to authenticate", err)
	}
}

// TestEnteInitTokenMasterKeyWithPassword pins the priority shift: with
// password set, token + master_key now goes through password mode, and the
// master_key field is treated as stale and ignored.
func TestEnteInitTokenMasterKeyWithPassword(t *testing.T) {
	acc := newSrpAccount(t, testEmail, testPassword)
	m := newMockEnte(t)
	attrs, err := json.Marshal(map[string]any{"hasSetKeys": true, "keyAttributes": acc.keyAttrs})
	if err != nil {
		t.Fatal(err)
	}
	m.keyAttrs = string(attrs)

	addition := accountAddition(acc.tokenB64, m.URL)
	addition.Password = testPassword
	d := newTestDriver(t, addition)
	if !bytes.Equal(d.masterKey, acc.masterKey) {
		t.Error("master key should come from keyAttributes, not the stale master_key field")
	}
}

func TestEnteRegistration(t *testing.T) {
	ctor, err := op.GetDriver("Ente")
	if err != nil {
		t.Fatalf("GetDriver: %v", err)
	}
	cfg := ctor().Config()
	if cfg.Name != "Ente" {
		t.Errorf("Name = %q, want Ente", cfg.Name)
	}
	if !cfg.MustProxy() {
		t.Error("MustProxy() = false, want true: Ente bytes are E2EE ciphertext")
	}
	if !cfg.NoUpload {
		t.Error("NoUpload = false, want true: the driver is read-only")
	}
	if cfg.DefaultRoot != "root" {
		t.Errorf("DefaultRoot = %q, want root", cfg.DefaultRoot)
	}
}

func TestEnteAdminForm(t *testing.T) {
	info, ok := op.GetDriverInfoMap()["Ente"]
	if !ok {
		t.Fatal("Ente missing from the driver info map")
	}
	items := map[string]driver.Item{}
	for _, it := range info.Additional {
		items[it.Name] = it
	}
	for name, required := range map[string]bool{
		"email": false, "password": false, "two_fa_secret": false,
		"token": false, "master_key": false, "secret_key": false, "show_hidden": false, "endpoint": false,
	} {
		it, ok := items[name]
		if !ok {
			t.Errorf("admin form is missing %q", name)
			continue
		}
		if it.Required != required {
			t.Errorf("%s required = %v, want %v", name, it.Required, required)
		}
	}
	if got := items["endpoint"].Default; got != "https://api.ente.com" {
		t.Errorf("endpoint default = %q, want https://api.ente.com", got)
	}
	if got := items["show_hidden"].Default; got != "false" {
		t.Errorf("show_hidden default = %q, want false", got)
	}
	if got := items["root_folder_path"].Default; got != "root" {
		t.Errorf("root_folder_path default = %q, want root", got)
	}
}
