package ente

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"math/big"
	"testing"

	"golang.org/x/crypto/blake2b"
	"golang.org/x/crypto/nacl/box"
	"golang.org/x/crypto/nacl/secretbox"
)

// Golden vectors cross-generated by the TS reference implementation in
// OpenList-APIPages (frontend/src/lib/ente/crypto.ts + @noble/hashes +
// @ente-io/srp). Password: "correct horse battery staple".
const (
	vecKekSaltB64 = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
	vecKekB64     = "ctSY8Ug7YNUekdPuynD4sUUbaRCLyLkmanMMQFqxNp4="
	vecLoginKeyB6 = "SlPDTwDuc2yL3N6nMOa/+A=="

	vecSrpSaltB64 = "BwcHBwcHBwcHBwcHBwcHBw=="
	vecSrpAB64    = "dBUqOuqRTDyboISzIJv/pwZvkxTBn+8IhlJEOjS2nck/47TNobF6RyVRr5cJxsAZS+Udl5esGUvb1+gTHr9v+MfKBHtDXSDyA32aLoM1mn4ZYXYovNR9cEod/DueO+VSc8mbwS6O203qdFgjYMKFNV05S89QouPcTpl+RjYNQxCFtmzMBCsCBG3Gh/FBqNfXPJMTC9e487BS2OmWcOmKWdwyMMUrHZuZ56FGQ4C5VLoeixU1CLa8dDwSxOMM2dCPoNMqDBqlBPp81MyVHA3VH5bPjiyCfozpHFNz9VakjJKoJJ1e/KjQ6HjHWN7DFz2IrkKnWqaRIaYHWkhYbkbWXgJ+FmdIFIUu7Qa3Y6672wp/96nuAuRpxuFNZTvpBdCQY0bvzSwPSVQkns05suNSw8dmy0fFwr2P+z13UYALHS6zmLayLhRCx+75gL1VsV7uXflIgT+bKTHveFU2G9kG8t2BE3vJR3NxF8J5cWy7k038hd24APbMNSuWb0vgz0VRXbiPJBYNPSTNAiOOVLlzJLflPTSH3Xg9xPzJQx81nRow++B/+P31nzq14dd2QGalZFIu/2jOQQxgBM3gCCBr+ArmDD9iaF/yk2N+3gMVkbc27VB+9VTIOU2KXA0wd51SLgHVtMU+u84YMTm5JHMuV7+k/im0ESng9Nyp19oTgaA="
	vecSrpBB64    = "J781ilg+Gag1epEVvrDAUiVI30pSgy6DU/qSLttPJhnp07rlqVcwPO0hQUGGPg0NJd03AMBV9hYLmnHUr/uOSf7AsIsROvhQGP6KFC3WekZdCy9Nn038GXg7ith7GYVj+1jdvywEkDfDRbrB0jFt5Fvf9SiLNzqqj6gAQ5p0vdTqwMflYlyWHexQ1ypV1zBupwKniVJwVt0P4rC1MiJ9cnyRV9cz+u/W9oWzp0uIj5WjtyR6XTbjeuWJ5JlORoTVhmgO5bIz0qPsZMkA+folNE8tEypezatrb1+xREknOM9Li1STPAu31y9arNG2UJXnaHZWNxAARzdpJhW909Z50rNXJdVwwd802AYkr8WEOeKYKrm465MMrh5N5VMkEcGqHvd+sCCZpb3uaZDHNp1QcdsP1rK8EentocCFdSrp5axZxtFCjo7H3n2STcCrAXmoMAkNMfJWGgDg5ccQedgFw5F9TGyCAlOhLMwcxM49LSchw6A1txLYVU+08fYm4ZSzWO3DG95L2eBsjsjGwuIa4UZWDUFE8eF/HP1z1z+l0EQkEh5Ukc/d45XdPOrTlpuV60kXK9WYLNZ2iJgMnV8To6Hwzr+nSXBAgG+OQXeQpY+sKShggkSAU+zDTACK3lGrHh90XFsz5MMuqUIEClIxv0XyTjywrnu8gWOOs9mjmYk="
	vecM1B64      = "nIPDAQZS/q0IpwOSZy4RAprAJaWr+iB4oK8pCj3nzDE="
	vecM2B64      = "cqoWbbRXKZoxdGzBTeX27i3IFKjqlepwLQhAXETxa+4="
	vecM2WrongB64 = "cqoWbbRXKZoxdGzBTeX27i3IFKjqlepw0ghAXETxa+4="
)

func TestDeriveKEKVector(t *testing.T) {
	kek, err := deriveKEK("correct horse battery staple", mustB64Decode(t, vecKekSaltB64), 3, 8192)
	if err != nil {
		t.Fatalf("deriveKEK: %v", err)
	}
	if got := base64.StdEncoding.EncodeToString(kek); got != vecKekB64 {
		t.Fatalf("kek mismatch: got %s", got)
	}
}

func TestDeriveKEKRejectsInvalidLimits(t *testing.T) {
	salt := mustB64Decode(t, vecKekSaltB64)
	if _, err := deriveKEK("pw", salt, 0, 8192); err == nil {
		t.Fatal("opsLimit=0 accepted")
	}
	if _, err := deriveKEK("pw", salt, 3, 1023); err == nil {
		t.Fatal("memLimit=1023 accepted")
	}
}

func TestDeriveLoginKeyVector(t *testing.T) {
	key, err := deriveLoginKey(mustB64Decode(t, vecKekB64))
	if err != nil {
		t.Fatalf("deriveLoginKey: %v", err)
	}
	if got := base64.StdEncoding.EncodeToString(key); got != vecLoginKeyB6 {
		t.Fatalf("loginKey mismatch: got %s", got)
	}
}

// TestBlake2bParamMatchesXCrypto pins the hand-written compress function
// against x/crypto/blake2b on the key-only configuration (zero salt and
// personal), which the latter supports. This guards the padding and key
// block logic the parameterized path shares.
func TestBlake2bParamMatchesXCrypto(t *testing.T) {
	key := mustB64Decode(t, vecKekB64)
	data := []byte("ente blake2b equivalence probe \x00\xff data")
	want, err := blake2b.New(32, key)
	if err != nil {
		t.Fatal(err)
	}
	want.Write(data)
	got, err := blake2bParamSum(32, key, make([]byte, 16), make([]byte, 16), data)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want.Sum(nil)) {
		t.Fatal("parameterized blake2b diverges from x/crypto")
	}
}

func TestSrpSessionVectors(t *testing.T) {
	identity := []byte("12345")
	salt := mustB64Decode(t, vecSrpSaltB64)
	loginKey := mustB64Decode(t, vecLoginKeyB6)
	secret1 := bytes.Repeat([]byte{0x42}, 32)
	s, err := newSrpSession(identity, salt, loginKey, secret1)
	if err != nil {
		t.Fatalf("newSrpSession: %v", err)
	}
	if got := base64.StdEncoding.EncodeToString(s.computeA()); got != vecSrpAB64 {
		t.Fatalf("srpA mismatch")
	}
	m1, err := s.computeM1(mustB64Decode(t, vecSrpBB64))
	if err != nil {
		t.Fatalf("computeM1: %v", err)
	}
	if got := base64.StdEncoding.EncodeToString(m1); got != vecM1B64 {
		t.Fatalf("srpM1 mismatch: got %s", got)
	}
	if !s.verifyM2(mustB64Decode(t, vecM2B64)) {
		t.Fatal("valid srpM2 rejected")
	}
	if s.verifyM2(mustB64Decode(t, vecM2WrongB64)) {
		t.Fatal("tampered srpM2 accepted")
	}
}

// TestSrpRoundTrip runs the server side of SRP-6a in-test (museum semantics,
// k and padding shared with the client code) and checks both parties derive
// matching M1/M2.
func TestSrpRoundTrip(t *testing.T) {
	identity := []byte("9999")
	salt := make([]byte, 16)
	rand.Read(salt)
	password := mustB64Decode(t, vecLoginKeyB6)
	s, err := newSrpSession(identity, salt, password, nil)
	if err != nil {
		t.Fatal(err)
	}
	// server: verifier v = g^x, ephemeral b, B = (k*v + g^b) mod N
	x := new(big.Int).SetBytes(srpHash(salt, srpHash(identity, []byte(":"), password)))
	v := new(big.Int).Exp(big.NewInt(srpG), x, srpN)
	b := big.NewInt(0x7777)
	B := new(big.Int).Exp(big.NewInt(srpG), b, srpN)
	B.Add(B, new(big.Int).Mul(srpK, v))
	B.Mod(B, srpN)
	m1, err := s.computeM1(padSRP(B))
	if err != nil {
		t.Fatal(err)
	}
	// server: u, S = (A * v^u)^b = A^b * v^(u*b), M1 = H(padA, padB, padS)
	u := new(big.Int).SetBytes(srpHash(padSRP(s.A), padSRP(B)))
	S := new(big.Int).Exp(s.A, b, srpN)
	S.Mul(S, new(big.Int).Exp(v, new(big.Int).Mul(u, b), srpN))
	S.Mod(S, srpN)
	sBytes := padSRP(S)
	k := srpHash(sBytes)
	srvM1 := srpHash(padSRP(s.A), padSRP(B), sBytes)
	if !bytes.Equal(m1, srvM1) {
		t.Fatal("client and server M1 disagree")
	}
	if !s.verifyM2(srpHash(padSRP(s.A), srvM1, k)) {
		t.Fatal("server M2 rejected")
	}
}

func TestOpenKeyAttributes(t *testing.T) {
	masterKey := mustB64Decode(t, masterKeyB64)
	secretKey := mustB64Decode(t, boxSecretB64)
	kek := mustB64Decode(t, vecKekB64)
	masterCipher, masterNonce := sealSecretbox(t, masterKey, kek)
	secretCipher, secretNonce := sealSecretbox(t, secretKey, masterKey)
	attrs := enteKeyAttributes{
		KEKSalt:                  vecKekSaltB64,
		EncryptedKey:             masterCipher,
		KeyDecryptionNonce:       masterNonce,
		EncryptedSecretKey:       secretCipher,
		SecretKeyDecryptionNonce: secretNonce,
	}
	gotMaster, gotSecret, err := openKeyAttributes(attrs, kek)
	if err != nil {
		t.Fatalf("openKeyAttributes: %v", err)
	}
	if !bytes.Equal(gotMaster, masterKey) || !bytes.Equal(gotSecret, secretKey) {
		t.Fatal("decrypted keys mismatch")
	}
	_, _, err = openKeyAttributes(attrs, bytes.Repeat([]byte{1}, 32))
	if err == nil || !bytes.Contains([]byte(err.Error()), []byte("wrong password")) {
		t.Fatalf("wrong kek error = %v", err)
	}
}

func TestOpenToken(t *testing.T) {
	secretKey := mustB64Decode(t, boxSecretB64)
	pk, err := boxPublicKey(secretKey)
	if err != nil {
		t.Fatal(err)
	}
	// seal a token the way the museum server does: ephemeral keypair with
	// the nonce derived from epk ‖ recipientPK
	esecret := make([]byte, 32)
	rand.Read(esecret)
	epk, err := boxPublicKey(esecret)
	if err != nil {
		t.Fatal(err)
	}
	nonceHash, err := blake2b.New(24, nil)
	if err != nil {
		t.Fatal(err)
	}
	nonceHash.Write(epk)
	nonceHash.Write(pk)
	var nonce [24]byte
	copy(nonce[:], nonceHash.Sum(nil))
	var epkArr, pkArr, skArr, eskArr [32]byte
	copy(epkArr[:], epk)
	copy(pkArr[:], pk)
	copy(skArr[:], secretKey)
	copy(eskArr[:], esecret)
	token := []byte("raw-token-bytes")
	sealed := append(append([]byte{}, epk...), box.Seal(nil, token, &nonce, &pkArr, &eskArr)...)
	got, err := openToken(base64.StdEncoding.EncodeToString(sealed), base64.StdEncoding.EncodeToString(pk), secretKey)
	if err != nil {
		t.Fatalf("openToken: %v", err)
	}
	if !bytes.Equal(got, token) {
		t.Fatal("token mismatch")
	}
	if _, err := openToken(base64.StdEncoding.EncodeToString(sealed[:40]), base64.StdEncoding.EncodeToString(pk), secretKey); err == nil {
		t.Fatal("truncated sealed box accepted")
	}
}

func TestAuthResponseTwoFactorSessionID(t *testing.T) {
	if r := (&authResponse{}).twoFactorSessionID(); r != "" {
		t.Fatal("empty response returned a session")
	}
	if r := (&authResponse{TwoFactorSessionIDV2: "v2"}).twoFactorSessionID(); r != "v2" {
		t.Fatal("V2 fallback broken")
	}
	if r := (&authResponse{TwoFactorSessionID: "v1", TwoFactorSessionIDV2: "v2"}).twoFactorSessionID(); r != "v1" {
		t.Fatal("V1 should win")
	}
}

// --- test helpers -----------------------------------------------------------

func mustB64Decode(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("bad base64 fixture %q: %v", s, err)
	}
	return b
}

// sealSecretbox returns cipher and nonce base64 sealed under key.
func sealSecretbox(t *testing.T, plain, key []byte) (cipherB64, nonceB64 string) {
	t.Helper()
	var keyArr [32]byte
	copy(keyArr[:], key)
	var nonce [24]byte
	rand.Read(nonce[:])
	return base64.StdEncoding.EncodeToString(secretbox.Seal(nil, plain, &nonce, &keyArr)),
		base64.StdEncoding.EncodeToString(nonce[:])
}
